name: 'send-slack-notification'
description: 'use this for sending json payload as notification to slack'
inputs:
  payload-file-path:
    description: 'Input environment variable'
    required: true
  channel-id:
    description: 'Input channel id'
    required: true
  slack-bot-token:
    description: 'Slack bot token'
    required: true
  github_repository:
    description: 'Input github repository'
    required: true
  github_branch:
    description: 'Input github branch'
    required: true
  github_run_id:
    description: 'Input github branch'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Store User Side Json
      run: |
        # Read the contents of the payload.json file and store it in an environment variable
        payload_content=$(cat "${{ inputs.payload-file-path }}")
        echo "PAYLOAD_JSON=$payload_content >> $GITHUB_ENV"
      shell: bash

    - name: payload modify through shell command
      working-directory: ${{github.action_path}}
      run: |
        pwd
        ls
        chmod +x payload_modify.bash
        ./payload_modify.bash $PAYLOAD_JSON
      shell: bash      
            
    - name: send to payload to slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload-file-path: ${{ inputs.payload-file-path }}
        channel-id: ${{ inputs.channel-id }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}

