name: 'send-slack-notification'
description: 'use this for sending json payload as notification to slack'
inputs:
  payload-file-path:
    description: 'Input environment variable'
    required: true
  channel-id:
    description: 'Input channel id'
    required: true
  slack-bot-token:
    description: 'Slack bot token'
    required: true
  github_repository:
    description: 'Input github repository'
    required: true
    default: ${{ github.event.inputs.github_repository }}
  github_branch:
    description: 'Input github branch'
    required: true
    default: ${{ github.event.inputs.github_branch }}
  github_run_id:
    description: 'Input github branch'
    required: true
    default: ${{ github.event.inputs.github_run_id }}

runs:
  using: 'composite'
  steps:
    - name: payload modify through shell command
      run: |
        chmod +x ./report-to-slack/payload_modify.bash
        ./report-to-slack/payload_modify.bash
      shell: bash
            
    - name: send to payload to slack
      uses: slackapi/slack-github-action@v1.24.0 
      with:
        payload-file-path: ${{ inputs.payload-file-path }}
        channel-id: ${{ inputs.channel-id }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}

