name: 'send-slack-notification'
description: 'use this for sending json payload as notification to slack'
inputs:
  payload-file-path:
    description: 'Input environment variable'
    required: False
  channel-id:
    description: 'Input channel id'
    required: true
  slack-bot-token:
    description: 'Slack bot token'
    required: true
  github_repository:
    description: 'Input github repository'
    required: true
  github_branch:
    description: 'Input github branch'
    required: true
  github_run_id:
    description: 'Input github branch'
    required: true

runs:
  using: 'composite'
  steps:
    - name: payload modify through shell command
      run: |
        sed -i "s|git_repo|${{ inputs.github_repository }}|g; s|git_branch|${{ inputs.github_branch }}|g; s|git_run_id|${{ inputs.github_run_id }} |g" "${{ inputs.payload-file-path }}"
        chmod +x ./payload_modify.bash
        ./payload_modify.bash ${{ inputs.payload-file-path }}
      shell: bash
            
    - name: send to payload to slack
      uses: slackapi/slack-github-action@v1.24.0 
      with:
        payload-file-path: "./reusable-payload_v3.json"
        channel-id: ${{ inputs.channel-id }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}

