name: Slack Notification Using payload
description: Using common json payload template send the notification to slack
inputs:
  GITHUB_REPOSITORY:
    description: 'github_repository'
    required: true
    default: 'default_value'
  GITHUB_BRANCH:
    description: 'github_branch'
    required: true
    default: 'default_value'
  GITHUB_RUN_ID:
    description: 'github_run_id'
    required: true
    default: 'default_value'
  TEST_REPORTS_LINK:
    description: 'github_run_id'
    required: true
    default: 'default_value'  
# runs:
#   using: 'composite'
#   steps:
#     - name: Replace Json Payload With Variables
#       run: |
#           sed -i "s|github_repo|${{inputs.GITHUB_REPOSITORY}}|g; s|github_branch|${{inputs.GITHUB_BRANCH}}|g; s|test_report_link|${{inputs.TEST_REPORTS_LINK}}|g; s|run_id|${{inputs.GITHUB_RUN_ID}}|g" util/slack-notification/reusable-payload.json
#       shell: bash

#     - name: Show updated JSON
#       run: cat util/slack-notification/reusable-payload.json
#       shell: bash

#     - name: Run the script
#       run: |
#         npm install axios
#         node util/slack-notification/index.js
#       shell: 'bash'

runs:
  using: 'docker'
  image: 'Dockerfile'
      




    