name: 'send-slack-notification'
description: 'use this for sending json payload as notification to slack'
inputs:
  payload-file-path:
    description: 'Input environment variable'
    required: false
  channel-id:
    description: 'Input channel id'
    required: true
  slack-bot-token:
    description: 'Slack bot token'
    required: true
  github_repository:
    description: 'Input github repository'
    required: true
  github_branch:
    description: 'Input github branch'
    required: true
  github_run_id:
    description: 'Input github branch'
    required: true

runs:
  using: 'composite'
  steps:

    - name: List Environment Variables
      run: |
        env_json="{"

        # Loop through environment variables
        for key in "${!env[@]}"; do
          # Check if the variable is not "COLOR_CODE" to exclude it
          if [ "$key" != "COLOR_CODE" ]; then
            # Add the key-value pair to the JSON-like string
            env_json="$env_json\"$key\":\"${env[$key]}\","
          fi
        done

        # Remove the trailing comma and close the JSON-like string
        env_json="${env_json%,}"
        env_json="$env_json}"

        # Print the JSON-like string
        echo "$env_json"

      shell: bash

    

    # - name: payload modify through shell command
    #   run: |
    #     chmod +x ./report-to-slack/payload_modify.bash
    #     ./report-to-slack/payload_modify.bash "${{ inputs.payload-file-path }}"
    #   shell: bash
            
    # - name: send to payload to slack
    #   uses: slackapi/slack-github-action@v1.24.0
    #   with:
    #     payload-file-path: ${{ inputs.payload-file-path }}
    #     channel-id: ${{ inputs.channel-id }}
    #   env:
    #     SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}

