name: "Run Shell Command and Send to Slack"
description: "Run a shell command and send the output to Slack."
inputs:
  payload_file_path:
    description: "Path to the payload file"
    required: true

  # shell_command:
  #   description: "Shell command to be executed"
  #   required: true

  slack_bot_token:
    description: "Slack bot token"
    required: true

  slack_channel_id:
    description: "Slack channel ID"
    required: true


runs:
  using: 'docker'
  image: 'Dockerfile'