name: Slack Notification Using payload
description: Using common json payload template send the notification to slack
inputs:
  GITHUB_REPOSITORY:
    description: 'github_repo'
    required: true
    default: ''
  GITHUB_BRANCH:
    description: 'github_branch'
    required: true
    default: ''
  GITHUB_RUN_ID:
    description: 'github_run_id'
    required: true
    default: ''
  TEST_REPORTS_LINK:
    description: 'github_run_id'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Replace Json Payload With Variables
      run: |
          sed -i "s|github_repo|${{inputs.GITHUB_REPOSITORY}}|g; s|github_branch|${{inputs.GITHUB_BRANCH}}|g; s|test_report_link|${{inputs.TEST_REPORTS_LINK}}|g; run_id|${{inputs.GITHUB_RUN_ID}}|g" util/payload-slack-content.json
      shell: bash

    - name: Show updated JSON
      run: cat util/payload-slack-content.json
      shell: bash
    
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload-file-path: util/payload-slack-content.json
      




    