name: Send Slack Notification With Dynamic Payload

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Replace variables
        run: |
          chmod +x ./report-to-slack/payload_modify.bash
          ./report-to-slack/payload_modify.bash
          echo ./reusable-payload.json
      
      - name: Send Slack Notification
        uses: ./report-to-slack
        with:
          GITHUB_REPOSITORY: ${{ github.ref_name }}
          GITHUB_BRANCH: "testing"
          GITHUB_RUN_ID: ${{ github.run_id }}
          TEST_REPORTS_LINK: "TBD"
        env:
          SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL }}"
