name: Send Slack Notification With Dynamic Payload

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Send Slack Notification
        uses: ./.github/actions/slack_notification/
        with:
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_BRANCH: "${{ github.ref_name }}"
          GITHUB_RUN_ID: "${{ github.run_id }}"
          TEST_REPORTS_LINK: "value need to be given"
          GITHUB_WORKFLOW: https://github.com/github_repo/actions/runs/run_id
        env:
          SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL }}"