name: Slack Notification

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Replace Json Payload With Variables
        env:
          JSON_FILE_PATH: ./payload-slack-content.json
        run: |
          sed -i "s|var1|REPLACED_VAR1|g" $JSON_FILE_PATH
          sed -i "s|var2|REPLACED_VAR2|g" $JSON_FILE_PATH
          sed -i "s|var3|REPLACED_VAR3|g" $JSON_FILE_PATH

      - name: Show updated JSON
        run: echo $JSON_FILE_PATH