name: Slack Notification

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Replace Json Payload With Variables
        env:
          JSON_FILE_PATH: payload-slack-content.json
        run: |
          sed -i 's/var1/${{ github.repository }}/g' $JSON_FILE_PATH
          sed -i 's/var2/${{ github.ref_name }}/g' $JSON_FILE_PATH
          sed -i 's/var3/${{ github.run_id }}/g' $JSON_FILE_PATH

      - name: Show updated JSON
        run: cat $JSON_FILE_PATH