name: Slack Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    end-slack-notification:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Fail Step Testing
          id: fail-step
          run: |
            ./payload_modify.bash
            echo "::set-output name=failed::$(if [ $? -eq 0 ]; then echo 'false'; else echo 'true'; fi)"
  
        - name: Set color based on the previous step
          run: |
            if [[ "${{ steps.fail-step.outputs.failed }}" == "true" ]]; then
              echo "STATUS_COLOR=#FF0000" >> $GITHUB_ENV
            else
              echo "STATUS_COLOR=36a64f" >> $GITHUB_ENV
            fi

        - name: payload modify through shell command
          if: always()
          run: |
            chmod +x ./report-to-slack/payload_modify.bash
            ./report-to-slack/payload_modify.bash               

        - name: send to payload to slack
          if: always()
          uses: slackapi/slack-github-action@v1.24.0 
          with:
            payload-file-path: ./report-to-slack/reusable-payload.json
            channel-id: 'C060KE84MB6'
            
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}