name: Slack Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    end-slack-notification:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Read JSON payload from file
          id: read_payload
          run: |
            echo "SLACK_PAYLOAD=$(cat slack_payload.json)" >> $GITHUB_ENV
        - name: Post to a Slack channel
          id: slack
          uses: slackapi/slack-github-action@v1.24.0
          with:
            # Slack channel id, channel name, or user id to post message.
            # See also: https://api.slack.com/methods/chat.postMessage#channels
            # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
            channel-id: 'C060KE84MB6'
            # For posting a simple plain text message
            slack-message: ${{ steps.read_payload.outputs.payload }}
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
