name: Slack Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    end-slack-notification:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Set color based on the previous step
          run: echo "STATUS_COLOR=$(if [ $? -eq 0 ]; then echo '36a64f'; else echo 'E92020'; fi)" >> $GITHUB_ENV

        - name: payload modify
          run: |
            chmod +x ./report-to-slack/payload_modify.bash
            ./report-to-slack/payload_modify.bash
            cat ./report-to-slack/reusable-payload.json
          env:
            github_repository: ${{ github.repository }}
            github_branch: ${{ github.ref_name }}
            github_run_id: ${{ github.run_id }}
            test_report_link: "TBD"
            status_color: ${{ env.STATUS_COLOR }}

        - name: Run shell command and send to Slack
          id: run_shell_command
          uses: slackapi/slack-github-action@v1.24.0 
          with:
            payload_file_path: './report-to-slack/reusable-payload.json'
            slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }} 
            slack_channel_id: 'C060KE84MB6'