name: Slack Notification

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Replace Json Payload With Variables
        run: |
          sed -i "s|var1|REPLACED_VAR1|g" payload-slack-content.json

      - name: Show updated JSON
        run: echo payload-slack-content.json