name: Slack Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    end-slack-notification:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: payload modify through shell command
          run: |
            echo '{}' > output.json  # Initialize an empty JSON object

            # Loop through environment variables starting with INPUT_ENV_
            for var in $(compgen -e | grep -E '^INPUT_ENV_'); do
              var_name=${var#"INPUT_ENV_"}  # Extract variable name
              var_value=${!var}             # Extract variable value
              echo "$(jq --arg var_name "$var_name" --arg var_value "$var_value" '.[$var_name] = $var_value' output.json)" > output.json
            done
            cat output.json
          env:
            TEST_1: sample_value
            TEST_2: sample_value
            TEST_3: sample_value

        