name: Slack Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    end-slack-notification:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Replace variables
          run: |
            chmod +x ./report-to-slack/payload_modify.bash
            ./report-to-slack/payload_modify.bash
            cat ./report-to-slack/reusable-payload.json

        - name: Read JSON payload from file
          id: read_payload
          run: |
            echo "SLACK_PAYLOAD=$(cat report-to-slack/reusable-payload.json)" >> $GITHUB_ENV
        - name: Post to a Slack channel
          id: slack
          uses: slackapi/slack-github-action@v1.24.0
          with:
            channel-id: 'C060KE84MB6'
            slack-message: ${{ steps.read_payload.outputs.payload }}
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
