name: Slack Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    end-slack-notification:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: payload modify
          run: |
            chmod +x ./report-to-slack/payload_modify.bash
            ./report-to-slack/payload_modify.bash        

        # - name: Run shell command and send to Slack
        #   id: run_shell_command
        #   uses: slackapi/slack-github-action@v1.24.0 
        #   with:
        #     payload-file-path: ./report-to-slack/reusable-payload.json
        #     channel-id: 'C060KE84MB6'
            
        #   env:
        #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}