name: Slack Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    Send-slack-notification:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4            

        - name: payload modify through shell command
          run: |
            chmod +x ./report-to-slack/payload_modify.bash
            ./report-to-slack/payload_modify.bash
          
        - name: send to payload to slack
          uses: slackapi/slack-github-action@v1.24.0 
          with:
            payload-file-path: ./report-to-slack/reusable-payload.json
            channel-id: 'C06168TBVT8'
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        