name: Slack Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    Send-slack-notification:
      runs-on: ubuntu-latest
      steps:          
        - name: send to payload to slack
          uses: ./.github/actions/my-composite-action 
          with:
            payload-file-path: "./report-to-slack/reusable-payload.json"
            channel-id: "C06168TBVT8"
            slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
            
        